nuget:
  account_feed: true
  
init:
  - git config --global core.autocrlf true
  
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - cmd: nuget sources add -Name AspNetVNext -Source https://www.myget.org/F/aspnetvnext/api/v2
 - cmd: nuget sources add -Name Autofac -Source https://www.myget.org/F/autofac/

before_build:
 - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm list
 - ps: dnvm install 1.0.0-beta7
 - ps: dnvm list
 - ps: dnvm update-self
 - ps: dnvm list
 - ps: dnvm upgrade
 - ps: dnvm list
 - ps: dnvm use 1.0.0-beta7
 - ps: dnvm list
 - ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore
 #- ps: nuget restore
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
